name = "DiffEqOperators"
uuid = "9fdde737-9c7f-55bf-ade8-46b3f136cc48"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "4.30.0"

[deps]
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
BlockBandedMatrices = "ffab5731-97b5-5995-9138-79e8c1846df0"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LazyBandedMatrices = "d7e5e226-e90b-4449-9968-0f923699bf6f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
SuiteSparse = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"

[compat]
BandedMatrices = "0.15.11, 0.16"
BlockBandedMatrices = "0.8.6, 0.9, 0.10"
DiffEqBase = "6.4.1"
DomainSets = "0.5"
ForwardDiff = "0.10"
LazyArrays = "0.17, 0.18, 0.19, 0.20, 0.21"
LazyBandedMatrices = "0.3, 0.4, 0.5"
ModelingToolkit = "4 - 5.20, 5"
NNlib = "0.6, 0.7"
NonlinearSolve = "0.3.7"
RuntimeGeneratedFunctions = "0.4, 0.5"
SciMLBase = "1.11"
StaticArrays = "0.10, 0.11, 0.12, 1.0"
SymbolicUtils = "0.11, 0.12, 0.13"
julia = "1"

[extras]
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["FillArrays", "OrdinaryDiffEq", "Parameters", "Random", "SafeTestsets", "SpecialFunctions", "Test"]
